In [1]:
import pandas as pd

In [2]:
df_customers = pd.read_csv('~/Downloads/interview_customers.csv')

In [3]:
df_orders = pd.read_csv('~/Downloads/interview_orders.csv')

In [4]:
df_customers

                                               email_hash country gender  age
0       7401e6dc3157063539c2533ec2817d019a2893c1315ef1...      CZ      M   68
1       7cb26098a184e9d5926350ac5dbab0a30542a35d1d97ec...      CZ      F   58
2       aba0a668a308b8d2a962bf0737c26bbcf268e231e4c266...      CZ      F   69
3       c49630270d4ebca2cd51ef76bfdbdc1724f1bce9b8d565...      CZ      F   19
4       78e37fb07e9969e3cc283c69efde40229c95fa49b1f11a...      CZ      M   12
...                                                   ...     ...    ...  ...
143995  8bc6f99cfea26a2164d33e11c9cdbc2dddd13bffd0cf70...      SK      F   21
143996  a60c380fd3e2584d997df2b3ef305aed32852610d11c71...      CZ      M   84
143997  95cd387442c8aa568cd6dd6d375625de4ba88db2659390...      CZ      M   59
143998  bbfecbc9256708c1a932f9eb97f7f4cd264b142d0eb5f2...      CZ      F   27
143999  112d14e21c72a54f8fee13d41f4c45461a9a5dc0790c40...      SK      M   42

[144000 rows x 4 columns]

In [5]:
df_orders

,order_id,date,sales_channel,order_currency,books_count,total_price,status_canceled,country,email_hash
0,1356102,1699228800000,E-shop,CZK,NaN,39.20000,1,CZ,7401e6dc3157063539c2533ec2817d019a2893c1315ef1...
1,1305120,1697673600000,E-shop,CZK,1.0,53.60000,0,CZ,7cb26098a184e9d5926350ac5dbab0a30542a35d1d97ec...
2,1369685,1699660800000,E-shop,CZK,1.0,176.80000,0,CZ,aba0a668a308b8d2a962bf0737c26bbcf268e231e4c266...
3,1298151,1697414400000,E-shop,EUR,1.0,32.87700,0,SK,c49630270d4ebca2cd51ef76bfdbdc1724f1bce9b8d565...
4,1250809,1695772800000,E-shop,CZK,1.0,486.40000,0,CZ,78e37fb07e9969e3cc283c69efde40229c95fa49b1f11a...
...,...,...,...,...,...,...,...,...,...
206357,1185905,1693612800000,E-shop,CZK,2.0,152.80000,0,CZ,a60c380fd3e2584d997df2b3ef305aed32852610d11c71...
206358,1219295,1694995200000,E-shop,CZK,1.0,144.00000,0,CZ,95cd387442c8aa568cd6dd6d375625de4ba88db2659390...
206359,1117911,1690502400000,E-shop,CZK,3.0,608.00000,0,CZ,d0a429b5a24d71cb312c6486d0632098a3f9d9dad2d6ee...
206360,1230308,1695254400000,E-shop,CZK,6.0,800.80000,0,CZ,bbfecbc9256708c1a932f9eb97f7f4cd264b142d0eb5f2...
206361,1317101,1698019200000,E-shop,EUR,3.0,41.16735,0,SK,112d14e21c72a54f8fee13d41f4c45461a9a5dc0790c40...

In [6]:
#mergnutie tabuliek na zaklade email hashu,
df_merged = pd.merge(df_orders, df_customers, on='email_hash', how='inner')

In [7]:
print(df_orders['email_hash'].duplicated().sum())
print(df_customers['email_hash'].duplicated().sum())
#nedava zmysel odstranovat duplicity u email_hash, pretoze 1 mail moze mat viac objednavok

62362
0

In [8]:
#prevod casu
df_merged['date'].unique()

array([1699228800000, 1704240000000, 1697673600000, 1699660800000,
       1704585600000, 1702512000000, 1696291200000, 1697414400000,
       1688256000000, 1695772800000, 1688169600000, 1700697600000,
       1697587200000, 1701907200000, 1695340800000, 1698278400000,
       1699401600000, 1694217600000, 1700006400000, 1694563200000,
       1694649600000, 1690070400000, 1693440000000, 1694995200000,
       1702857600000, 1688342400000, 1705363200000, 1702080000000,
       1702944000000, 1688860800000, 1700265600000, 1704672000000,
       1699833600000, 1689638400000, 1697328000000, 1696896000000,
       1705104000000, 1695168000000, 1695427200000, 1688601600000,
       1702598400000, 1700870400000, 1688428800000, 1690416000000,
       1700438400000, 1698451200000, 1699056000000, 1689379200000,
       1696809600000, 1701993600000, 1698969600000, 1703980800000,
       1702771200000, 1698364800000, 1698624000000, 1688774400000,
       1695081600000, 1690243200000, 1704499200000, 1701561600000,
       1700352000000, 1691971200000, 1693785600000, 1696636800000,
       1694131200000, 1694044800000, 1691107200000, 1688515200000,
       1696550400000, 1704326400000, 1696118400000, 1691193600000,
       1704153600000, 1704758400000, 1701388800000, 1689292800000,
       1691452800000, 1694476800000, 1698105600000, 1693699200000,
       1702166400000, 1705190400000, 1691798400000, 1702684800000,
       1700092800000, 1701216000000, 1705017600000, 1697500800000,
       1698883200000, 1689552000000, 1701302400000, 1698710400000,
       1704412800000, 1698796800000, 1697846400000, 1698192000000,
       1700179200000, 1701648000000, 1697155200000, 1699142400000,
       1701820800000, 1699488000000, 1699574400000, 1702252800000,
       1698537600000, 1699747200000, 1705276800000, 1693526400000,
       1704844800000, 1704931200000, 1700524800000, 1694908800000,
       1702425600000, 1697932800000, 1700956800000, 1705708800000,
       1702339200000, 1705536000000, 1705449600000, 1690502400000,
       1693094400000, 1693180800000, 1701129600000, 1690588800000,
       1703808000000, 1703289600000, 1703030400000, 1691020800000,
       1705622400000, 1701043200000, 1690675200000, 1699315200000,
       1701734400000, 1695686400000, 1698019200000, 1703116800000,
       1694304000000, 1699920000000, 1704067200000, 1691366400000,
       1695859200000, 1688688000000, 1697241600000, 1691712000000,
       1692835200000, 1703635200000, 1689465600000, 1693267200000,
       1693353600000, 1689120000000, 1692921600000, 1693958400000,
       1703894400000, 1692576000000, 1692748800000, 1688947200000,
       1696377600000, 1692662400000, 1700784000000, 1689033600000,
       1694390400000, 1689724800000, 1693872000000, 1695513600000,
       1695254400000, 1696982400000, 1703721600000, 1692316800000,
       1692403200000, 1692489600000, 1696464000000, 1696032000000,
       1690329600000, 1695945600000, 1692230400000, 1689206400000,
       1690848000000, 1701475200000, 1696723200000, 1694822400000,
       1697760000000, 1703203200000, 1690934400000, 1697068800000,
       1693612800000, 1696204800000, 1691625600000, 1690761600000,
       1690156800000, 1689897600000, 1694736000000, 1703462400000,
       1692057600000, 1691280000000, 1703376000000, 1695600000000,
       1689811200000, 1691884800000, 1700611200000, 1693008000000,
       1691539200000, 1689984000000, 1692144000000, 1705795200000,
       1703548800000])

In [15]:
from datetime import datetime

# prevod Unix casu
data = {'date': [1699228800000, 1704240000000, 1697673600000, 1699660800000,
       1704585600000, 1702512000000, 1696291200000, 1697414400000,
       1688256000000, 1695772800000, 1688169600000, 1700697600000,
       1697587200000, 1701907200000, 1695340800000, 1698278400000,
       1699401600000, 1694217600000, 1700006400000, 1694563200000,
       1694649600000, 1690070400000, 1693440000000, 1694995200000,
       1702857600000, 1688342400000, 1705363200000, 1702080000000,
       1702944000000, 1688860800000, 1700265600000, 1704672000000,
       1699833600000, 1689638400000, 1697328000000, 1696896000000,
       1705104000000, 1695168000000, 1695427200000, 1688601600000,
       1702598400000, 1700870400000, 1688428800000, 1690416000000,
       1700438400000, 1698451200000, 1699056000000, 1689379200000,
       1696809600000, 1701993600000, 1698969600000, 1703980800000,
       1702771200000, 1698364800000, 1698624000000, 1688774400000,
       1695081600000, 1690243200000, 1704499200000, 1701561600000,
       1700352000000, 1691971200000, 1693785600000, 1696636800000,
       1694131200000, 1694044800000, 1691107200000, 1688515200000,
       1696550400000, 1704326400000, 1696118400000, 1691193600000,
       1704153600000, 1704758400000, 1701388800000, 1689292800000,
       1691452800000, 1694476800000, 1698105600000, 1693699200000,
       1702166400000, 1705190400000, 1691798400000, 1702684800000,
       1700092800000, 1701216000000, 1705017600000, 1697500800000,
       1698883200000, 1689552000000, 1701302400000, 1698710400000,
       1704412800000, 1698796800000, 1697846400000, 1698192000000,
       1700179200000, 1701648000000, 1697155200000, 1699142400000,
       1701820800000, 1699488000000, 1699574400000, 1702252800000,
       1698537600000, 1699747200000, 1705276800000, 1693526400000,
       1704844800000, 1704931200000, 1700524800000, 1694908800000,
       1702425600000, 1697932800000, 1700956800000, 1705708800000,
       1702339200000, 1705536000000, 1705449600000, 1690502400000,
       1693094400000, 1693180800000, 1701129600000, 1690588800000,
       1703808000000, 1703289600000, 1703030400000, 1691020800000,
       1705622400000, 1701043200000, 1690675200000, 1699315200000,
       1701734400000, 1695686400000, 1698019200000, 1703116800000,
       1694304000000, 1699920000000, 1704067200000, 1691366400000,
       1695859200000, 1688688000000, 1697241600000, 1691712000000,
       1692835200000, 1703635200000, 1689465600000, 1693267200000,
       1693353600000, 1689120000000, 1692921600000, 1693958400000,
       1703894400000, 1692576000000, 1692748800000, 1688947200000,
       1696377600000, 1692662400000, 1700784000000, 1689033600000,
       1694390400000, 1689724800000, 1693872000000, 1695513600000,
       1695254400000, 1696982400000, 1703721600000, 1692316800000,
       1692403200000, 1692489600000, 1696464000000, 1696032000000,
       1690329600000, 1695945600000, 1692230400000, 1689206400000,
       1690848000000, 1701475200000, 1696723200000, 1694822400000,
       1697760000000, 1703203200000, 1690934400000, 1697068800000,
       1693612800000, 1696204800000, 1691625600000, 1690761600000,
       1690156800000, 1689897600000, 1694736000000, 1703462400000,
       1692057600000, 1691280000000, 1703376000000, 1695600000000,
       1689811200000, 1691884800000, 1700611200000, 1693008000000,
       1691539200000, 1689984000000, 1692144000000, 1705795200000,
       1703548800000]}
df_merged['date'] = pd.to_numeric(df_merged['date'], errors='coerce')

df_merged['formatted_date'] = pd.to_datetime(df_merged['date'], unit='ms')

df_merged['formatted_date'].isna()
df_merged = df_merged.dropna(subset=['formatted_date'])

In [14]:
import numpy as np

def find_print_outliers(df_orders, books_count):
    Q1 = df_orders[books_count].quantile(0.25)
    Q3 = df_orders[books_count].quantile(0.75)
    IQR = Q3 - Q1
    
    # Definovanie outliers
    outliers = df_orders[(df_orders[books_count] < (Q1 - 1.5 * IQR)) | (df_orders[books_count] > (Q3 + 1.5 * IQR))]
    
    if not outliers.empty:
        print(f"Outliers in {books_count}:")
        print(outliers)
    else:
        print(f"No outliers in {books_count}")

find_print_outliers(df_orders, 'total_price')

find_print_outliers(df_orders, 'books_count')


if not np.issubdtype(df_orders['date'].dtype, np.datetime64):
    df_orders['date'] = pd.to_datetime(df_orders['date'], unit='ms')
find_print_outliers(df_orders, 'date')

Outliers in total_price:
        order_id           date sales_channel order_currency  books_count  \
40       1358988  1699315200000        E-shop            CZK          4.0
41       1440770  1701734400000        E-shop            CZK          9.0
46       1538407  1704585600000        E-shop            CZK          4.0
58       1487070  1702771200000        E-shop            CZK          1.0
60       1197247  1694131200000        E-shop            CZK          2.0
...          ...            ...           ...            ...          ...
206267   1389996  1700265600000        E-shop            CZK          3.0
206268   1193654  1693958400000        E-shop            CZK         23.0
206288   1308919  1697760000000        E-shop            CZK          6.0
206320   1261934  1696204800000        E-shop            CZK          4.0
206360   1230308  1695254400000        E-shop            CZK          6.0

        total_price  status_canceled country  \
40            962.4                0      CZ
41           1219.2                0      CZ
46            829.6                0      CZ
58           1005.6                0      CZ
60           1251.2                0      CZ
...             ...              ...     ...
206267        824.8                0      CZ
206268       1560.8                0      CZ
206288        904.0                0      CZ
206320        974.4                0      CZ
206360        800.8                0      CZ

                                               email_hash
40      e7e51107bfc86a418287518fe40e6dc93894404d50b32b...
41      0458762c8be13bfaf99e8911622df9715a2944d4ac9ac9...
46      e61041e6bee170e7703878a6d448997642d5559bc66f5a...
58      1f64ea792ebc9877ebbf8d1c6e400592ffd78442b5e386...
60      56f5761474f814489d3edf0a0e4b4a09e0143287fa612b...
...                                                   ...
206267  ba522acf3008f463220dbd9fe318c6f9b36d4debf62aff...
206268  0b54eefc5cc0eb48ad5114d1b344865f0ca7a68e2b7d6b...
206288  9c5df9676f22e4b808016baacae7c797635b3c01653b40...
206320  664a724fd18778d7510da77c359f64664b074071a76b27...
206360  bbfecbc9256708c1a932f9eb97f7f4cd264b142d0eb5f2...

[12730 rows x 9 columns]
Outliers in books_count:
        order_id           date sales_channel order_currency  books_count  \
13       1557969  1705104000000        E-shop            CZK         11.0
20       1390110  1700265600000        E-shop            EUR         15.0
41       1440770  1701734400000        E-shop            CZK          9.0
56       1527404  1704326400000   Marketplace            EUR          8.0
71       1079198  1688428800000        E-shop            CZK         10.0
...          ...            ...           ...            ...          ...
206268   1193654  1693958400000        E-shop            CZK         23.0
206270   1259030  1696118400000        E-shop            EUR         28.0
206274   1519153  1704067200000        E-shop            CZK          8.0
206316   1096597  1689379200000        E-shop            CZK          8.0
206338   1163956  1692662400000        E-shop            CZK          7.0

        total_price  status_canceled country  \
13        188.80000                0      CZ
20        169.38855                0      SK
41       1219.20000                0      CZ
56         41.20000                0      DE
71        668.00000                0      CZ
...             ...              ...     ...
206268   1560.80000                0      CZ
206270     54.50805                0      SK
206274    258.40000                0      CZ
206316    536.80000                0      CZ
206338    736.80000                0      CZ

                                               email_hash
13      5c9c777e5d5a3b2de757c3c47195b3d0773b7a576db95f...
20      622b90bb4202a12b3153f1f80be2c56572fd865894696f...
41      0458762c8be13bfaf99e8911622df9715a2944d4ac9ac9...
56      6c091a68fd4c9fb101fb4ab1b328c4a634a2186c242725...
71      e7dfe55da18bb648bb4454b78e79b67440238eade02303...
...                                                   ...
206268  0b54eefc5cc0eb48ad5114d1b344865f0ca7a68e2b7d6b...
206270  2d2393ac03e889c8f20e6d000db3211326c0b1982c310f...
206274  e1b5c905209de65028aa366855c5ace39fada5bbd054c1...
206316  1dad9468ea8e9dd4e9c05b5cda478126edd0de5963dea4...
206338  626927ada26f3252577813933242c26489eb6c041a4073...

[13786 rows x 9 columns]
No outliers in date

In [16]:
columns_to_check = ['age', 'total_price', 'books_count']

for column in columns_to_check:
    print(f"--- {column} ---")
    
# 10 najvacssich values
    print("10 Highest Values:")
    print(df_merged[column].nlargest(10))
    
# 10 najmensich values
    print("10 Lowest Values:")
    print(df_merged[column].nsmallest(10))
    

    print("\n")

--- age ---
10 Highest Values:
154653    142
5023      135
5024      135
5025      135
5026      135
5027      135
5028      135
5029      135
5030      135
5031      135
Name: age, dtype: int64
10 Lowest Values:
138657   -38
49157    -37
49158    -37
81928    -36
194016   -36
132747   -34
163092   -32
136306   -27
160121   -27
52837    -25
Name: age, dtype: int64


--- total_price ---
10 Highest Values:
153830    44694.4
109678    40128.0
96823     29632.0
113347    25292.8
11108     24428.0
130692    22960.0
1095      22444.0
22079     18089.6
139670    15626.4
94066     15116.0
Name: total_price, dtype: float64
10 Lowest Values:
192371   -146.4
191918    -69.6
43636     -64.0
22980     -43.2
134537    -28.8
92772     -27.2
186994    -20.0
47053     -16.0
72087     -12.8
15056     -10.4
Name: total_price, dtype: float64


--- books_count ---
10 Highest Values:
125167    220.0
86049     200.0
92423     185.0
1095      175.0
114655    167.0
22079     161.0
114657    141.0
7363      139.0
33008     133.0
96910     128.0
Name: books_count, dtype: float64
10 Lowest Values:
1     1.0
2     1.0
3     1.0
5     1.0
7     1.0
8     1.0
9     1.0
10    1.0
31    1.0
33    1.0
Name: books_count, dtype: float64

In [17]:
# zobrazit hodnoty nad urcitu hodnotu
for column in columns_to_check:
    count_under_zero = (df_merged[column] >100).sum()
    print(f"Number of values under 0 in {column}: {count_under_zero}")

Number of values under 0 in age: 1100
Number of values under 0 in total_price: 127855
Number of values under 0 in books_count: 18

In [18]:
#priemerny vek pre hodnoty medzi 10-100
average_age = df_merged[(df_merged['age'] >= 10) & (df_merged['age'] <= 100)]['age'].mean()

#nahradit vek pod 10 a nad 100 priemerom
df_merged.loc[(df_merged['age'] < 10) | (df_merged['age'] > 100), 'age'] = average_age

print(average_age)

50.38521218640135

In [19]:
#check order_id column, negativne hodnoty a hodnoty s menej nez 7 charactermi
negative_order_ids = df_merged[df_merged['order_id'] < 0]

non_seven_char_order_ids = df_merged[~df_merged['order_id'].astype(str).str.match(r'^\d{7}$')]
print("Negative Order IDs:")
print(negative_order_ids)

print("\nOrder IDs with Non-7 Characters:")
print(non_seven_char_order_ids)

Negative Order IDs:
Empty DataFrame
Columns: [order_id, date, sales_channel, order_currency, books_count, total_price, status_canceled, country_x, email_hash, country_y, gender, age, formatted_date]
Index: []

Order IDs with Non-7 Characters:
Empty DataFrame
Columns: [order_id, date, sales_channel, order_currency, books_count, total_price, status_canceled, country_x, email_hash, country_y, gender, age, formatted_date]
Index: []

In [20]:
#chybajuce hodnoty napriec datafromom
missing_values_count = df_merged.isna().sum()

print("Count of NaN or NaT per column:")
print(missing_values_count)

Count of NaN or NaT per column:
order_id               0
date                   0
sales_channel          0
order_currency         0
books_count        13201
total_price            0
status_canceled        0
country_x              0
email_hash             0
country_y              0
gender                 0
age                    0
formatted_date         0
dtype: int64

In [33]:
#uprava books_count riadkov u zrusenych objednavok s nenulovou hodnotou


#Počet riadkov so statusom 'status_canceled' rovným 1
cancelled_count = (df_merged['status_canceled'] == 1).sum()

#Počet riadkov, kde 'books_count' má hodnotu NaN
nan_books_count = df_merged['books_count'].isna().sum()

#rozdiel
mismatch = cancelled_count - nan_books_count

print(f"Počet riadkov so status_canceled = 1: {cancelled_count}")
print(f"Počet riadkov s NaN v books_count: {nan_books_count}")
print(f"Rozdiel: {mismatch}")

#Riadky so statusom zrušené
status_canceled_rows = df_merged[df_merged['status_canceled'] == 1]

#Riadky, kde 'books_count' je NaN
nan_books_count_rows = df_merged[df_merged['books_count'].isna()]

#riadky,ktoré  sú v 'status_canceled_rows', ale nie v 'nan_books_count_rows'
mismatch_rows = status_canceled_rows[~status_canceled_rows.index.isin(nan_books_count_rows.index)]

# books_count' na NaN pre riadky, kde je rozdiel
df_merged.loc[mismatch_rows.index, 'books_count'] = np.nan

Počet riadkov so status_canceled = 1: 13574
Počet riadkov s NaN v books_count: 13577
Rozdiel: -3

In [34]:

df_merged

,order_id,date,sales_channel,order_currency,books_count,total_price,status_canceled,country_x,email_hash,country_y,gender,age,formatted_date
0,1356102,1699228800000,E-shop,CZK,NaN,39.20000,1,CZ,7401e6dc3157063539c2533ec2817d019a2893c1315ef1...,CZ,M,68.0,2023-11-06
1,1525560,1704240000000,E-shop,CZK,1.0,132.80000,0,CZ,7401e6dc3157063539c2533ec2817d019a2893c1315ef1...,CZ,M,68.0,2024-01-03
2,1305120,1697673600000,E-shop,CZK,1.0,53.60000,0,CZ,7cb26098a184e9d5926350ac5dbab0a30542a35d1d97ec...,CZ,F,58.0,2023-10-19
3,1369685,1699660800000,E-shop,CZK,1.0,176.80000,0,CZ,aba0a668a308b8d2a962bf0737c26bbcf268e231e4c266...,CZ,F,69.0,2023-11-11
4,1539904,1704585600000,E-shop,CZK,6.0,909.60000,0,CZ,aba0a668a308b8d2a962bf0737c26bbcf268e231e4c266...,CZ,F,69.0,2024-01-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...
206357,1414070,1700956800000,E-shop,CZK,1.0,237.60000,0,CZ,8bc6f99cfea26a2164d33e11c9cdbc2dddd13bffd0cf70...,SK,F,21.0,2023-11-26
206358,1185905,1693612800000,E-shop,CZK,2.0,152.80000,0,CZ,a60c380fd3e2584d997df2b3ef305aed32852610d11c71...,CZ,M,84.0,2023-09-02
206359,1219295,1694995200000,E-shop,CZK,1.0,144.00000,0,CZ,95cd387442c8aa568cd6dd6d375625de4ba88db2659390...,CZ,M,59.0,2023-09-18
206360,1230308,1695254400000,E-shop,CZK,6.0,800.80000,0,CZ,bbfecbc9256708c1a932f9eb97f7f4cd264b142d0eb5f2...,CZ,F,27.0,2023-09-21
206361,1317101,1698019200000,E-shop,EUR,3.0,41.16735,0,SK,112d14e21c72a54f8fee13d41f4c45461a9a5dc0790c40...,SK,M,42.0,2023-10-23

In [35]:
#zaokruhlenie total price
df_merged['total_price'] = df_merged['total_price'].round(3)

In [54]:
#ulozenie mergnuteho filu
df_merged.to_excel('/Users/katka/Downloads/knihobot_file2.xlsx', index=False)